name: 00 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    # with:
    #   # Eğer build.yml'ye argümanlar göndermeniz gerekiyorsa buraya ekleyin
    #secrets:
      #inherit: true
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

  sca:
    needs: build
    name: Static Code Analysis
    uses: ./.github/workflows/sca.yml
    # with:
    #   # Eğer sca.yml'ye argümanlar göndermeniz gerekiyorsa buraya ekleyin
    # secrets:
    #   inherit: true
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

  sast:
    needs: build
    name: Static Application Security Testing
    uses: ./.github/workflows/sast.yml
    # secrets:
    #   inherit: true