name: 00 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    # with:
    #   # Eğer build.yml'ye argümanlar göndermeniz gerekiyorsa buraya ekleyin
    secrets:
      inherit: true
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
